In [2]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [3]:
data = pd.read_csv('ev_fg_per_game.csv')

In [5]:
# data

In [6]:
data.isna().sum().sum()

0

In [7]:
data['YEAR_1'] = data['YEAR'].str.split('-').str[0]

In [9]:
# data

In [12]:
data

,YEAR,FGM_PER_GAME,FGA_PER_GAME,FG2M_PER_GAME,FG2A_PER_GAME,FG3M_PER_GAME,FG3A_PER_GAME,FTM_PER_GAME,FTA_PER_GAME,YEAR_1
0,1998-99,34.168966,78.196552,29.714483,65.033793,4.455172,13.165517,18.779310,25.796552,1998
1,1999-00,36.831034,82.096552,31.992431,68.379310,4.837931,13.717241,18.965517,25.282759,1999
2,2000-01,35.682759,80.603448,30.841463,66.891085,4.841379,13.706897,18.593103,24.879310,2000
3,2001-02,36.172414,81.268966,30.954163,66.521867,5.213793,14.755172,17.913793,23.827586,2001
4,2002-03,35.710345,80.782759,30.587468,66.104710,5.134483,14.675862,18.506897,24.431034,2002
5,2003-04,35.006897,79.817241,29.828848,64.890664,5.182759,14.920690,18.193103,24.203448,2003
6,2004-05,35.943333,80.336667,30.348780,64.584553,5.600000,15.750000,19.700000,26.056667,2004
7,2005-06,35.836667,78.990000,30.113821,63.008943,5.726667,15.983333,19.600000,26.303333,2005
8,2006-07,36.526667,79.710000,30.460976,62.764634,6.070000,16.940000,19.616667,26.080000,2006
9,2007-08,37.260000,81.510000,30.709350,63.397154,6.563333,18.106667,18.850000,24.940000,2007
10,2008-09,37.113333,80.916667,30.470732,62.793089,6.653333,18.133333,19.056667,24.736667,2008
11,2009-10,37.696667,81.693333,31.263415,63.563821,6.440000,18.136667,18.623333,24.543333,2009
12,2010-11,37.246667,81.210000,30.787805,63.202033,6.463333,18.010000,18.603333,24.366667,2010
13,2011-12,36.476667,81.430000,30.063131,63.045455,6.406667,18.386667,16.896667,22.463333,2011
14,2012-13,37.120000,82.026667,29.974867,62.059104,7.163333,19.966667,16.706667,22.190000,2012
15,2013-14,37.716667,83.000000,29.969512,61.462602,7.743333,21.536667,17.836667,23.593333,2013
16,2014-15,37.516667,83.563333,29.669512,61.151626,7.850000,22.410000,17.136667,22.846667,2014
17,2015-16,38.230000,84.570000,29.720325,60.491057,8.506667,24.083333,17.690000,23.353333,2015
18,2016-17,39.050000,85.416667,29.395528,58.411789,9.650000,27.003333,17.833333,23.110000,2016
19,2017-18,39.606667,86.063333,29.117073,57.060163,10.486667,28.996667,16.613333,21.673333,2017
20,2018-19,41.073333,89.213333,29.718293,57.201626,11.360000,32.006667,17.676667,23.073333,2018
21,2019-20,40.830000,88.800000,28.634486,54.708991,12.193333,34.103333,17.846667,23.096667,2019
22,2020-21,41.210000,88.416667,28.515278,53.778241,12.706667,34.636667,16.970000,21.816667,2020
23,2021-22,40.623333,88.090000,28.183740,52.921545,12.440000,35.180000,16.933333,21.856667,2021
24,2022-23,41.976667,88.316667,29.634553,54.086992,12.340000,34.210000,18.393333,23.530000,2022